// Build config.both.yaml, the one Ergogen config for both halves (generated, gitignored).
// config.yaml already mirrors every point into the right half (points.mirror). Ergogen cannot mirror a
// polygon, or an outline built from other outlines, so each outline gets a "<name>_right" twin that refers
// to the mirrored points, each case gets a twin built from those, and Edge.Cuts takes both halves.
const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

const cfg = yaml.load(fs.readFileSync(path.join(__dirname, 'config.yaml'), 'utf8'))
const right = name => `${name}_right`

// A twin points at mirror_* refs; Ergogen negates shifts in x and turns on a mirrored point, so the
// numbers stay as written. A ref-less anchor would land on itself instead, so it is refused outright.
const twin = (node, names) => {
    if (Array.isArray(node)) return node.map(n => twin(n, names))
    if (!node || typeof node !== 'object') return node
    const out = {}
    for (const [k, v] of Object.entries(node)) out[k] = twin(v, names)
    if (typeof out.ref === 'string') out.ref = `mirror_${out.ref}`
    if (typeof out.where === 'string' && out.where.startsWith('/^')) out.where = out.where.replace('/^', '/^mirror_')
    if (out.where && typeof out.where === 'object' && !Array.isArray(out.where) && out.where.ref === undefined) {
        throw new Error(`where without a ref cannot mirror: ${JSON.stringify(node.where)}`)
    }
    if (typeof out.name === 'string' && names.includes(out.name)) out.name = right(out.name)
    return out
}

const outlines = Object.keys(cfg.outlines)
const cases = Object.keys(cfg.cases)
for (const n of outlines) cfg.outlines[right(n)] = twin(cfg.outlines[n], outlines)
for (const n of cases) cfg.cases[right(n)] = twin(cfg.cases[n], [...outlines, ...cases])
cfg.outlines.board_pcb_both = [
    {what: 'outline', name: 'board_pcb'},
    {operation: 'add', what: 'outline', name: right('board_pcb')},
]
cfg.pcbs.outline_only.outlines.edge.outline = 'board_pcb_both'

const header = '# GENERATED by make_both.js from config.yaml. Edit config.yaml, not this file.\n'
fs.writeFileSync(path.join(__dirname, 'config.both.yaml'), header + yaml.dump(cfg, {lineWidth: -1}))
console.log(`wrote config.both.yaml: ${outlines.length} outlines and ${cases.length} cases twinned for the right half`)
