// Build config.both.yaml, the one Ergogen config for both halves (generated, gitignored).
// config.yaml already mirrors every point into the right half (points.mirror). Ergogen cannot mirror a
// polygon, or an outline built from other outlines, so each outline gets a "<name>_right" twin that refers
// to the mirrored points, each case gets a twin built from those, and Edge.Cuts takes both halves.
const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

const cfg = yaml.load(fs.readFileSync(path.join(__dirname, 'config.yaml'), 'utf8'))
const right = name => `${name}_right`

// A twin points at mirror_* refs; Ergogen negates shifts in x and turns on a mirrored point, so the
// numbers stay as written. A ref-less anchor would land on itself instead, so it is refused outright.
const twin = (node, names) => {
    if (Array.isArray(node)) return node.map(n => twin(n, names))
    if (!node || typeof node !== 'object') return node
    const out = {}
    for (const [k, v] of Object.entries(node)) out[k] = twin(v, names)
    if (typeof out.ref === 'string') out.ref = `mirror_${out.ref}`
    if (typeof out.where === 'string' && out.where.startsWith('/^')) out.where = out.where.replace('/^', '/^mirror_')
    if (out.where && typeof out.where === 'object' && !Array.isArray(out.where) && out.where.ref === undefined) {
        throw new Error(`where without a ref cannot mirror: ${JSON.stringify(node.where)}`)
    }
    if (typeof out.name === 'string' && names.includes(out.name)) out.name = right(out.name)
    return out
}

const outlines = Object.keys(cfg.outlines)
const cases = Object.keys(cfg.cases)
for (const n of outlines) cfg.outlines[right(n)] = twin(cfg.outlines[n], outlines)
for (const n of cases) cfg.cases[right(n)] = twin(cfg.cases[n], [...outlines, ...cases])
// Assembly panel, so the fab does not choose it: a 5 mm process edge above and below both halves, joined to them
// by 5 mm breakoff tabs. Both halves hang from the same two rails, so the file is one board. Anchors are absolute
// Ergogen coordinates (y up, an anchor with no ref starts at the origin and shifts); KiCad x = 60 + x, y = 140 - y,
// the ORIGIN in scripts/place_from_ergogen.py. Every piece overlaps what it joins by 0.5 mm, because a rectangle
// that only touches an edge leaves a hairline T-joint.
//
// Tab positions are the windows where no track or pad comes within 3 mm of the board edge, and they stay clear of
// the USB-C cutouts in the top inner corners. The mouse bites, tooling holes, fiducials and the keepouts that hold
// the pours off the rails are footprints and rule areas, from scripts/place_panel.py.
const PANEL = [
    {name: 'rail top', where: {shift: [123.5, 87]}, size: [268, 5]},          // KiCad y 50.5..55.5
    {name: 'rail bottom', where: {shift: [123.5, -41.25]}, size: [268, 5]},   // KiCad y 178.75..183.75
    {name: 'tab top x77', where: {shift: [17, 81.25]}, size: [5, 7.5]},
    {name: 'tab top x113', where: {shift: [53, 83.69]}, size: [5, 2.62]},
    {name: 'tab top x149', where: {shift: [89, 81.56]}, size: [5, 6.88]},
    {name: 'tab top x218', where: {shift: [158, 81.56]}, size: [5, 6.88]},
    {name: 'tab top x254', where: {shift: [194, 83.69]}, size: [5, 2.62]},
    {name: 'tab top x290', where: {shift: [230, 81.25]}, size: [5, 7.5]},
    {name: 'tab bottom x95', where: {shift: [35, -34.59]}, size: [5, 9.33]},
    {name: 'tab bottom x135', where: {shift: [75, -34.59]}, size: [5, 9.33]},
    {name: 'tab bottom x232', where: {shift: [172, -34.59]}, size: [5, 9.33]},
    {name: 'tab bottom x272', where: {shift: [212, -34.59]}, size: [5, 9.33]},
]
// The FR4 plate ships on the same rails and tabs, so its mouse bites and tooling holes sit where the PCB's do
// (scripts/export_plate.py copies them from scripts/place_panel.py).
const panel = name => [
    {what: 'outline', name},
    {operation: 'add', what: 'outline', name: right(name)},
    ...PANEL.map(p => ({operation: 'add', what: 'rectangle', where: p.where, size: p.size})),
]
cfg.outlines.board_pcb_both = panel('board_pcb')
cfg.outlines.plate_panel = panel('plate_outline')
cfg.pcbs.outline_only.outlines.edge.outline = 'board_pcb_both'
cfg.pcbs.plate_only.outlines.edge.outline = 'plate_panel'

const header = '# GENERATED by make_both.js from config.yaml. Edit config.yaml, not this file.\n'
fs.writeFileSync(path.join(__dirname, 'config.both.yaml'), header + yaml.dump(cfg, {lineWidth: -1}))
console.log(`wrote config.both.yaml: ${outlines.length} outlines and ${cases.length} cases twinned for the right half`)
