// Derive the right half's Ergogen config from config.yaml, so geometry has one source.
// Mirrors every point about x = MIRROR_AXIS (Ergogen coordinates), keeps only the mirrored copies,
// and points the outlines at them. Writes config.right.yaml (generated, gitignored).
const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

// The left board spans Ergogen x -10.5 to 118.5; mirroring about 54 keeps the right board on the same sheet area.
const MIRROR_AXIS = 54
const SWAP_SIDE = { east: 'west', west: 'east' }

const cfg = yaml.load(fs.readFileSync(path.join(__dirname, 'config.yaml'), 'utf8'))
const mirror_x = x => 2 * MIRROR_AXIS - x

cfg.points.mirror = { ref: 'matrix_pinky_bottom', distance: 2 * MIRROR_AXIS }
cfg.points.key = { ...(cfg.points.key || {}), asym: 'clone' }

// Ergogen copies meta unchanged onto the mirror, so an LED facing east must be told to face west
const swap_led = key => {
    if (key && SWAP_SIDE[key.led]) key.mirror = { ...(key.mirror || {}), led: SWAP_SIDE[key.led] }
}
for (const zone of Object.values(cfg.points.zones)) {
    swap_led(zone.key)
    for (const col of Object.values(zone.columns || {})) swap_led(col && col.key)
    for (const row of Object.values(zone.rows || {})) swap_led(row)
}

// outlines: named refs and name filters move to the mirrored points; bare shifts (case ports, display) mirror by hand
const retarget = node => {
    if (Array.isArray(node)) return node.forEach(retarget)
    if (!node || typeof node !== 'object') return
    if (typeof node.ref === 'string') node.ref = `mirror_${node.ref}`
    if (typeof node.where === 'string' && node.where.startsWith('/^')) node.where = node.where.replace('/^', '/^mirror_')
    if (node.where && typeof node.where === 'object' && !node.where.ref && Array.isArray(node.where.shift)) {
        const [x, y] = node.where.shift
        node.where.shift = [typeof x === 'number' ? mirror_x(x) : `${2 * MIRROR_AXIS} - (${x})`, y]
    }
    Object.values(node).forEach(retarget)
}
retarget(cfg.outlines)

const header = '# GENERATED by make_right.js from config.yaml. Edit config.yaml, not this file.\n'
fs.writeFileSync(path.join(__dirname, 'config.right.yaml'), header + yaml.dump(cfg, { lineWidth: -1 }))
console.log('wrote config.right.yaml')
